### ISSUE TITLE
Java not found in snap

### ISSUE THREAD

**Issue by adriens** [adriens/schemacrawler-snapcraft#2]
```
0.87s$ sudo schemacrawler -help
/snap/schemacrawler/x1/schemacrawler-15.01.04-distribution/_schemacrawler/schemacrawler.sh: 3: /snap/schemacrawler/x1/schemacrawler-15.01.04-distribution/_schemacrawler/schemacrawler.sh: java: not found
```

**Comment by adriens** [comment]
https://forum.snapcraft.io/t/snapcraft-plugin-jdk-java-runtime-app-error/1403/3

**Comment by adriens** [comment]
https://github.com/ogra1/jtiledownloader/blob/master/snapcraft.yaml

**Comment by adriens** [comment]
https://docs.snapcraft.io/java-applications/7819

**Comment by adriens** [comment]
https://github.com/bsutton/tomcat-with-ssl-snap/blob/master/snapcraft.yaml

**Comment by adriens** [comment]
Asked for some help see https://forum.snapcraft.io/t/simple-jar-snap-with-bundled-jre/4598/4

**Comment by adriens** [comment]
Answer : https://forum.snapcraft.io/t/simple-jar-snap-with-bundled-jre/4598/5?u=adriens

```
apps:
  schemacrawler:
    command: schemacrawler-15.01.04-distribution/_schemacrawler/schemacrawler.sh
    environment: 
      JAVA_HOME: $SNAP/usr/lib/jvm/java-1.8.0-openjdk-$SNAP_ARCH
      PATH: $JAVA_HOME/bin:$JAVA_HOME/jre/bin:$PATH
```
